//add here most rarely modified headers to speed up debug build compilation

#include <memory>

#include "Util.h"
#include "UpdateFields.h"
#include "Transaction.h"
#include "Database/DatabaseEnv.h"
#include "DataStores/DBCStores.h"
#include "MapManager.h"
#include "Log.h"
#include "SpellMgr.h"
#include "ObjectAccessor.h"
#include "ObjectDefines.h"
#include "Opcodes.h"
#include "SharedDefines.h"
#include "ObjectMgr.h"
#include "Timer.h"
#include "Config.h"
#include "WorldSession.h"
#include "Unit.h"
#include "Creature.h"
#include "Player.h"
#include "World.h"
#include "Pet.h"
#include "CreatureAI.h"
#include "CreatureAINew.h"
#include "Item.h"
#include "SpellMgr.h"
#include "Bag.h"
#include "Mail.h"
#include "Corpse.h"