-- ALTER TABLE `creature_formations` 
--  ADD COLUMN `point_1` SMALLINT(5) UNSIGNED DEFAULT 0 NOT NULL AFTER `groupAI`,
--  ADD COLUMN `point_2` SMALLINT(5) UNSIGNED DEFAULT 0 NOT NULL AFTER `point_1`;
  