replace into `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`) values
('2','1','0','Yes, mighty $C, I sensed your arrival. I trust you have more news to report to me about your hunt?'),
('5','1','0','Oh, a shipment from my brother? Splendid! Fortune truly shines on me today!'),
('6','6','6','Did you find Garrick\'s shack? Are we finally free of that villain?'),
('7','1','6','How goes the hunting, $N? Have you found and defeated those vermin?'),
('8','6','0','Yes? Yes? What is it?$B$BThe forsaken; they certainly do have huge appetites. Make yourself at home... yes, rest those weary bones. My name\'s Renee if you need anything at all.'),
('9','1','6','Ah, I see you\'re back! I hope you\'ve been hard at work clearing those fields of those Harvest Watchers. Have you killed twenty yet?'),
('10','6','0','Well, what news do you have?  You look like you\'ve been in quite the fight... is Scrimshank alive?'),
('11','0','0','Hail, $N. Have you been killing Gnolls...?'),
('12','1','1','Perhaps I did not make myself clear, pledge. In order to prove your worth as a servant to The People\'s Militia and to the Light you need to slay 15 Defias Trappers and 15 Defias Smugglers then return to me when the deed is done.'),
('13','1','1','We have not time to talk, $N. The Defias Pillagers are denying the people of Westfall the peace and prosperity they deserve. Make sure at least 15 Defias Pillagers and 15 Defias Looters have been killed. That will send a clear message that corruption is not welcome here.'),
('14','1','1','$N, now is no time for idle chatter. If you still wish to prove yourself to The People\'s Militia you need to slay the Defias I notified you about earlier. Return to me when you have completed your duty.'),
('15','1','6','Have you been to the mines? Are you ready to report?'),
('16','0','0','Farming is thirsty work, and I\'m always looking for refreshing spring water.$B$BIf you have any, then I\'m willing to make a trade.'),
('17','6','6','Have you obtained the magenta fungus caps I need for my alchemical work? No caps - no reward!'),
('18','6','6','Have you gathered those bandanas for me yet?'),
('19','0','0','Orc pressure from Blackrock is still tense. But have you at least rid us of Tharil\'zun?'),
('20','0','0','Have you been slaying orcs, $N? If so, then show me...'),
('21','1','1','I know it\'s bloody work, $N, but it\'s vital to the safety of Northshire. Are you ready to report?'),
('22','5','4','All I need for my famous meat pie are 8 Goretusk Livers!'),
('23','6','0','Ah - $N - I was just thinking about you! How goes your hunting?'),
('24','6','0','Greetings once again, $N! Have you come to show me proof of your hunt?'),
('25','1','0','You back already? What\'s the situation out there - all cleared up now, thanks to you?'),
('26','1','0',''),
('27','1','0',''),
('30','1','0','Have you formed your pendant for me to inspect, $N? If you need help in locating the parts, try asking the local populace for information. Not only will you find what you seek, but it will give you a reason to explore this wondrous and sacred glade.'),
('31','1','0','Your return to Thunder Bluff is not without heralding, though I will need proof of your lessons learned in Moonglade before I will teach you your aquatic form.$B$BDo you have the Pendant of the Sea Lion?'),
('32','1','0','I\'m sorry. I don\'t know you... but from the look of things you have at least heard something of me. Now, what can I help you with? Do you have something for me?'),
('33','6','6','Hey $N. How goes the hunt for diseased young wolves?'),
('34','6','6','Is Bellygrub still at it or were you able to rid Lakeshire of the pest once and for all?'),
('35','1','0',NULL),
('36','6','6','I\'m going to miss that Verna Furlbrow so much. I don\'t suppose you happened to see her on your way here?'),
('37','1','0',NULL),
('38','1','1','Come back with the following ingredients: $b $b 3 Stringy Vulture Meat $b 3 Goretusk Snouts $b 3 Murloc Eyes $b 3 Okra'),
('39','1','0',NULL),
('40','1','0',NULL),
('45','1','0',NULL),
('46','0','0','How goes the hunting, $N?'),
('47','0','0','Psst! You have that Gold Dust for me...for me?'),
('48','94','94','Hiccup! Ho ho! You want an encore?$B$BIn the land to the south where vines twist and creep$BLies a hidden well where the water runs deep$BPure as the Light\'s sacred Daughter$BBring to me now some Holy Spring Water.'),
('49','94','94','Encore? Well, sure!$B$BAmber is the hue of my life\'s longest love$BLike the last embers of dusk in the sky above$BRetrieve for me so that my love shall be born$BOne sack of each: barley, rye and corn.'),
('50','94','94','An encore for you? Well sure friend!$B$BI\'ll mix and mix till we have a mash$BFor this will be our own private stash$BA still must be fashioned of metal strong$BBring me some Truesilver so I can finish this song.'),
('51','94','94','An encore? Why for you, anything!$B$BNot yet filtered but freshly distilled$BLike unseeded land waiting there tilled.$BNext I will fashion our pile of charcoal$BDeliver a sycamore branch, that is your next goal.'),
('52','1','0','Have you killed those wolves and bears?'),
('53','94','94','Sure, I\'ll sing it again for you, friend!$B$BMellifluous liquid clear as a baby\'s tears$BTurns a lovely deep amber over the years$BBut before we proceed to get lit to the hilt$BA barrel of charred oak must be built.'),
('54','1','0','You have word from McBride? Northshire is a garden compared to Elwynn Forest, but I wonder what Marshal McBride has to report.$b$bHere, let me have his papers...'),
('55','5','5','Is Morbent Fel defeated?!'),
('56','1','6','Have you killed those warriors and mages?'),
('57','1','25','Return to me once you have killed 15 Skeletal Fiends and 15 Skeletal Horrors, $N.'),
('58','1','25','I need your assistance, $N. Travel to the cemetery to the northwest and rid the eastern mausoleum of 20 Plague Spreaders.$B$BReturn to me when your task is complete.'),
('59','2','0','I have been commissioned by the Stormwind Army to supply their people with cloth and leather armor.$b$bIf you have a marker for me, then I\'d be happy to make you something.'),
('60','0','0','Did you gather those candles yet?'),
('61','0','0','Oh, a shipment from my brother? Splendid! Fortune truly shines on me today!'),
('62','1','0','What do you have to report, $N? Have you been to the Fargodeep Mine?'),
('63','1','0','The brazier still reflects the ambient light from the are, and the flame shifts slightly as you move closer.$B$BThe corruption along the hills seems to have kept its distance, and besides the missing components, the brazier looks prepared for the ritual to summon a cleansed manifestation of water.'),
('64','6','6','Don\'t suppose you were able to get my watch?'),
('65','1','0',NULL),
('66','1','0',NULL),
('67','1','0',NULL),
('68','6','6','Ah, I remember you. You\'re the one who was asking about that Stalvan fellow. Did you ever find what you were looking for?'),
('69','1','0',NULL),
('70','6','6','What have ya got there? Let me take a look at that. . .'),
('71','0','0','Hello, $N. Have you discovered the fates of Rolf and Malakai?'),
('72','1','0',NULL),
('74','6','6','What have you got there? I cannot see. My eyesight is very bad. Put it in my hands.'),
('75','6','6','Did you find that page I mentioned, $N?'),
('76','1','0','Hail, $N. What do you have to report? Have you scouted the Jasperlode Mine?'),
('77','6','0','I trust that your arrival here at our camp is to deliver the bottles of ripple that are integral to the task at hand, yes?'),
('78','6','6','Marshal Haggard sent you? Why didn\'t you say so?$B$BAh, good ol\' Haggard. Poor chap is going to be completely blind before long. Anyway, let me see what you\'ve got there.'),
('79','1','0','This better be good, $C. Let me see what you have and tell me your tale. But by the Light, be quick about it. Darkshire\'s defense is my number one priority. I have not the time to squander on dead-end leads.'),
('80','6','6','Back again, $N? What do you have this time?'),
('81','1','0','If you\'re not here to buy anything, and you\'re not here to deliver anything, then you\'re wasting my time! You better have that ripple!'),
('82','1','0','You\'re Junior Surveyor $N, yes? Quickly now, there is a dire situation at hand! Do you have the insect parts that Fizzledowser said you would?!'),
('83','6','6','I\'m running low on linen, $N. Do you have any for me?'),
('84','1','0','Ugh... I\'m starving! Do you have that pie for me, $N?'),
('85','1','0',NULL),
('86','6','6','I don\'t think it\'s right feeding the boy who stole my necklace in the first place, but if that\'s what it takes to get back what\'s mine, then so be it!$b$bDo you have that boar meat?'),
('87','3','3','Hello, $N. Have you found my necklace?'),
('88','6','6','Did you see her yet? Did you get her?'),
('89','6','6','This bridge isn\'t going to build itself! Now where are those iron pikes and iron rivets?'),
('90','6','6','Were you able to find 10 Lean Wolf Flanks yet? How about the herbs from Felicia in Stormwind?'),
('91','1','1','Turn in 10 Shadowhide Pendants to me, and you shall be rewarded.'),
('92','0','0','I still need five pieces of Tough Condor Meat, five Great Goretusk Snouts and five helpings of Crisp Spider Meat.'),
('93','3','3','Hail, $N. Did you get those Gooey Spider Legs yet?'),
('94','1','0','This Lion Statue has sat here for decades, and keeps a lonely watch over the infamous Tower of Ilgalar.$B$BThere is a depression at the base of the statue, where a gem or glyph might be set...'),
('95','1','0',NULL),
('96','1','0','You\'ve returned. Splendid!$B$BHow went your journey to Silverpine? Did it take you long?$B$BIt is hard for me to tell if you were successful there because so much of the land has become corrupt. Its stench overwhelms any good that you might have done. But small successes are sometimes as important as large ones. Purifying the water there was instrumental for you, and for all shamans.'),
('97','1','5','Yes, $N?'),
('98','6','6','Yes, $N?'),
('99','0','0','Have you secured the Pyrewood Shackles yet, $N?'),
('100','1','0',NULL),
('101','1','1','Bring to me 10 ghoul fangs, 10 skeleton fingers and 5 vials of spider venom. For you I shall enchant a Totem of Infliction which will harm those who attempt violent acts against you.'),
('102','6','6','Have you collected 8 paws from those treacherous Gnolls yet?'),
('103','0','0','The flame will not burn for long without oil, $N.'),
('104','0','0','Have you laid waste to the menace known as Old Murk-Eye yet? He has been spotted roaming the coastline of Westfall.$B$BReturn to me when the foul beast is dead.'),
('105','6','6','Your task has been given to you, $N. Do you have a shard from the lich\'s phylactery as proof of the task being accomplished?'),
('106','5','0','You have what?? Maybell is the light of my dull life. Hurry, let me see her letter!'),
('107','0','0','You have a note from \"Gramma\" Stonefield, eh? I haven\'t seen Mildred in years! I wonder what she has to say...'),
('109','1','0','An... Any luck??'),
('110','1','0',NULL),
('111','1','0','I can\'t wait to hear how my friends react!$B$BThey\'ll never expect it'),
('112','0','0','Do you have that crystal kelp? I\'m sure Maybell is anxious to see her beau...'),
('113','6','0','Well Junior Surveyor $n, has ol\' Pestlezugg got that report ready yet?'),
('114','0','0','Did you deliver my letter to Tommy Joe? What did he say??'),
('115','6','6','How goes your conflict with the shadowcasters? Did you find the midnight orbs?'),
('116','25','25','I need you to pick up a keg of Thunderbrew Lager from Grimbooze Thunderbrew in the Westfall hills, a cask of Merlot from Stormwind, a bottle of Moonshine from Darkshire and a skin of Sweet Rum from Goldshire. Bring those back to me and I will see to it you are rewarded.'),
('117','94','94','Hurry, my friend, move with haste $bIn order for our rich lager to taste $bMore like beer and less like stew, $bHops are needed to make the brew.'),
('118','0','0','What\'s that? Verner sent you, you say? Well give me his note. And SPEAK UP!'),
('119','0','0','Great, you\'re back! Did you get the shoes?'),
('120','6','6','What have you there?'),
('121','6','6','Did the General send news? Are reinforcements on the way?'),
('122','0','0','I know that greedy Argus will send someone to collect his scales if I don\'t give them to him soon. Have you found those scales yet?'),
('123','0','0','What?!? We haven\'t had our people working the Elwynn mines for months!$B$BLet me see that note you have...'),
('124','1','0','Yes? Is there something I can do for you?'),
('125','6','6','Were you able to find my tools?'),
('126','0','0','Yowler is a dangerous creature, $N. If you\'re not ready for him, I understand.'),
('127','0','0','You have some sunfish for me, eh?'),
('128','1','25','Return once you have slain 15 Blackrock Champions.'),
('129','0','0','Darcy sent me a lunch, did she? Such a kind heart she has. Well...let\'s have it!'),
('130','1','0',NULL),
('131','0','0','Hello again, $N. Did Parker like the lunch I sent him?'),
('132','6','0','Good to see you back, $N. What did Wiley have to say for himself?'),
('133','0','0','I think I hear a pack of Ghouls scurrying around the back of the house - I better put that effigy up quick! Did you get those Ghoul Ribs for me?'),
('134','0','0','Do you have my crate? If so, then please...give it to me quickly!'),
('135','6','0','What business do you have with me? I am a very busy man. . .'),
('136','1','0',NULL),
('138','1','0',NULL),
('139','1','0',NULL),
('140','1','0',NULL),
('141','6','0','Did Master Shaw shed any light on things?'),
('142','6','6','$N, were you able to gather any information? Did you locate the messenger?'),
('143','6','6','Hail, $C. What business do you have with The People\'s Militia?'),
('144','6','6','Shall we expect the People\'s Militia soon? Does Lord Stoutmantle\'s news bode well?'),
('145','6','6','You appear to have traveled from afar, $C. What business do you have here in Darkshire?'),
('146','6','6','Ah, good to see you back, messenger. Shall I inform the Marshal that the Night Watch is on its way from Darkshire?'),
('147','0','0','Did you find the Collector? Did you discover whom he\'s working for?'),
('148','1','0',NULL),
('149','1','0','Oh please, don\'t look at me! I tore out these eyes with my own hands, but I can still feel your gaze!$B$BI\'m hideous! Hideous! Please, look away!!'),
('150','0','0','Do you have those fins? Hurry, we need those murlocs driven from the lake!'),
('151','6','6','Old Blanchy is on her last leg. Did you happen to find any oats for her?'),
('152','1','0','Kill 7 Tidehunters, 7 Warriors, 7 Oracles and 7 Coastrunners and I will see to it that you are rewarded.'),
('153','1','1','Bring me 15 red leather bandanas and I\'ll pay you well.'),
('154','6','6','I sense that you have seen Blind Mary. You have my Comb...?'),
('155','1','0','What business do you have with me? I am a very busy man...'),
('156','6','6','Hi, $N. You have that rot blossoms for me yet?'),
('157','0','0','I need to string the Ghost Hair Thread along my door and my windows to keep out unwanted spirits. Did you get it for me?'),
('158','1','0',NULL),
('159','0','0','I need that Zombie Juice to keep me warm on these cold, dark nights. Did you get it for me?'),
('160','6','0','Abercrombie...? I don\'t know a person of that name. You say you have a letter for me from this Abercrombie fellow?$B$BWell let\'s have it then...'),
('161','6','0','You say somethin\', sonny? Can\'t hear a bloody thing besides the ringin\' in me ears. Say, what\'s that you got there?'),
('162','2','0','Peace and tranquility be upon you, stranger.  Why have you sought me out this day?'),
('163','1','0','Ah, $N! Back so soon? No doubt you\'ve been at the hunt again? Don\'t worry if you\'ve had some setbacks, in the long run it will make you better!$B$B...You couldn\'t get much worse, anyway...'),
('164','6','0','You look a sturdy type, $C. Have you come to join our fight?');