DELETE FROM gossip_text WHERE ID IN (738, 5996);
UPDATE creature_template SET ScriptName = "" WHERE entry = 3052;

UPDATE gossip_menu_option SET patch_min = 5 WHERE menu_id = 435 AND id IN (2,12); --barber and harbor
UPDATE gossip_menu_option SET patch_min = 5 WHERE menu_id = 421 AND id IN (8); --Inscription

UPDATE creature_template SET ScriptName = "", AIName = "SmartAI" WHERE entry = 7172;
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('7172','0','0','1','62','0','100','512','576','0','0','0','0','72','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Lore Keeper of Norgannon - On Gossip Option 0 Selected - Close Gossip');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('7172','0','1','0','61','0','100','512','0','0','0','0','0','26','2278','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Lore Keeper of Norgannon - On Gossip Option 0 Selected - Quest Credit \'The Platinum Discs\'');

UPDATE creature_template SET ScriptName = "", AIName = "SmartAI" WHERE entry = 6566;
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('6566','0','0','1','62','0','100','512','161','0','0','0','0','11','9949','2','0','0','0','0','7','0','0','0','0','0','0','0','0','Estelle Gendry - On Gossip Option 0 Selected - Invoker Cast \'Thieves\' Tool Rack Conjure\'');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('6566','0','1','0','61','0','100','512','161','0','0','0','0','72','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Estelle Gendry - On Gossip Option 0 Selected - Close Gossip');

UPDATE creature_template SET ScriptName = "", AIName = "SmartAI" WHERE entry IN (2238, 2239); 
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2238','0','0','0','38','0','100','0','1','1','0','0','0','80','223800','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Tog\'thar - On Data Set - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('2239','0','0','0','38','0','100','0','1','1','0','0','0','80','223900','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Drull - On Data Set - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('223800','9','0','0','0','0','100','0','0','0','0','0','0','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Tog\'thar - On Script - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('223800','9','1','0','0','0','100','0','4000','4000','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Tog\'thar - On Script - Say Line 1');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('223900','9','0','0','0','0','100','0','0','0','0','0','0','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Drull - On Script - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('223900','9','1','0','0','0','100','0','6000','6000','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Drull - On Script - Say Line 1');

replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('2238','0','0','Have you freed Drull yet? I don\'t know where he\'s being held.','12','1','100','6','0','0','593','0','Tog\'thar');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('2238','1','0','I will only slow you down, but no pink-skinned humans will keep me from freedom!','12','1','100','15','0','0','595','0','Tog\'thar');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('2239','0','0','Ah, it is good to be free of my bonds! Have you freed Tog\'thar yet? The humans split us up after our capture.','12','1','100','4','0','0','592','0','Drull');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('2239','1','0','Go on ahead without me! I will make my own way to Tarren Mill.','12','1','100','5','0','0','594','0','Drull');

UPDATE creature_template SET npcflag = 65537 WHERE entry = 3628;

ALTER TABLE `points_of_interest`   
  ADD COLUMN `patch` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `ID`, 
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`ID`, `patch`);
  
UPDATE points_of_interest SET patch = 5;

REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('40', 0, '-8975', '778.865', '6', '99', '0', 'Alchemy Needs', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('46', 0, '-8793', '741.886', '6', '99', '0', 'Arnold Leland', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('45', 0, '-8515', '804.505', '6', '99', '0', 'Shaina Fuller', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('44', 0, '-8348', '640.412', '6', '99', '0', 'Lilliam Sparkspindle', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('43', 0, '-8838', '782.35',  '6', '99', '0', 'Lucan Cordell', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('42', 0, '-8641', '423.502', '6', '99', '0', 'Pig and Whistle Tavern', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('41', 0, '-8433', '610.413', '6', '99', '0', 'Therum Deepforge', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('47', 0, '-8707', '462.037', '6', '99', '0', 'The Protective Hide', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('13', 0, '-8851', '856.599', '6', '99', '0', 'Stormwind Inscription', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('48', 0, '-8416', '672.791', '6', '99', '0', 'Gelman Stonehand', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('49', 0, '-8940', '771.346', '6', '99', '0', 'Duncan\'s Textiles', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('39', 0, '-8714', '342.761', '6', '99', '0', 'Stormwind Barracks', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('38', 0, '-8938', '986.894', '6', '99', '0', 'The Slaughtered Lamb', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('37', 0, '-9031', '549.835', '6', '99', '0', 'Farseer Umbrua', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('36', 0, '-8782', '353.099', '6', '99', '0', 'Stormwind - Rogue House', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('35', 0, '-8621', '777.189', '6', '99', '0', 'Cathedral Of Light', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('34', 0, '-9008', '857.193', '6', '99', '0', 'Wizard\'s Sanctum', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('33', 0, '-8430', '559.87',  '6', '99', '0', 'Hunter Lodge', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('32', 0, '-8749', '1075.78', '6', '99', '0', 'The Park', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('30', 0, '-8755', '657.7',   '6', '99', '0', 'Stormwind Barber', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('29', 0, '-8392', '272.087', '6', '99', '0', 'Battlemasters Stormwind', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('28', 0, '-8762', '401.972', '6', '99', '0', 'Champions\' Hall', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('27', 0, '-8796', '613.098', '6', '99', '0', 'Woo Ping', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('26', 0, '-8432', '555.121', '6', '99', '0', 'Jenova Stoneshield', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('25', 0, '-8425', '627.621', '6', '39', '0', 'Stormwind Locksmith', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('24', 0, '-8886', '595.38',  '6', '99', '0', 'Stormwind Visitor\'s Center', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('23', 0, '-8839', '487.546', '6', '99', '0', 'Stormwind Gryphon Master', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('22', 0, '-8867', '673.634', '6', '99', '0', 'The Gilded Rose', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('21', 0, '-8387', '565.012', '6', '99', '0', 'The Deeprun Tram', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('20', 0, '-8573', '990.095', '6', '0', '0', 'Stormwind Harbor', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('19', 0, '-8885', '640.052', '6', '99', '0', 'Stormwind Bank', '0');
REPLACE INTO points_of_interest (`ID`, `patch`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES ('18', 0, '-8812', '666.354', '6', '99', '0', 'Stormwind Auction House', '0');

UPDATE creature_template SET ScriptName = "", AIName = "SmartAI" WHERE entry = 7166;
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('7166','0','0','1','62','0','100','512','524','0','0','0','0','72','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Wrenixs Gizmotronic Apparatus - On Gossip Select - Close gossip');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('7166','0','1','0','61','0','100','512','0','0','0','0','0','11','9977','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Wrenixs Gizmotronic Apparatus - Cast Conjure E.C.A.C');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('7166','0','2','3','62','0','100','512','524','1','0','0','0','72','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Wrenixs Gizmotronic Apparatus - On Gossip Select - Close Gossip');
REPLACE INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('7166','0','3','0','61','0','100','512','0','0','0','0','0','11','9949','1','0','0','0','0','7','0','0','0','0','0','0','0','0','Wrenixs Gizmotronic Apparatus - Cast Thieves Tool Rack Conjure');
