ALTER TABLE disenchant_loot_template DROP FOREIGN KEY `disenchant_loot_template_ibfk_2`;
ALTER TABLE disenchant_loot_template ADD CONSTRAINT `disenchant_loot_template_ibfk_2` FOREIGN KEY (`Item`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_battleground_holiday   DROP FOREIGN KEY `game_event_battleground_holiday_ibfk_2`;
ALTER TABLE  game_event_battleground_holiday  ADD CONSTRAINT `game_event_battleground_holiday_ibfk_2` FOREIGN KEY (`event`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_condition   DROP FOREIGN KEY `game_event_condition_ibfk_2`;
ALTER TABLE  game_event_condition  ADD CONSTRAINT `game_event_condition_ibfk_2` FOREIGN KEY (`event_id`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_creature   DROP FOREIGN KEY `game_event_creature_ibfk_1`;
ALTER TABLE  game_event_creature  ADD CONSTRAINT `game_event_creature_ibfk_1` FOREIGN KEY (`guid`) REFERENCES `creature` (`spawnID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_creature_quest   DROP FOREIGN KEY `game_event_creature_quest_ibfk_1`;
ALTER TABLE  game_event_creature_quest  ADD CONSTRAINT `game_event_creature_quest_ibfk_1` FOREIGN KEY (`id`) REFERENCES `creature_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_creature_quest   DROP FOREIGN KEY `game_event_creature_quest_ibfk_2`;ALTER TABLE  game_event_creature_quest  ADD CONSTRAINT `game_event_creature_quest_ibfk_2` FOREIGN KEY (`quest`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE  game_event_creature_quest   DROP FOREIGN KEY `game_event_creature_quest_ibfk_3`;ALTER TABLE  game_event_creature_quest  ADD CONSTRAINT `game_event_creature_quest_ibfk_3` FOREIGN KEY (`event`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_gameobject   DROP FOREIGN KEY `game_event_gameobject_ibfk_1`;
ALTER TABLE  game_event_gameobject  ADD CONSTRAINT `game_event_gameobject_ibfk_1` FOREIGN KEY (`guid`) REFERENCES `gameobject` (`guid`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_gameobject_quest   DROP FOREIGN KEY `game_event_gameobject_quest_ibfk_1`;
ALTER TABLE  game_event_gameobject_quest  ADD CONSTRAINT `game_event_gameobject_quest_ibfk_1` FOREIGN KEY (`id`) REFERENCES `gameobject_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_gameobject_quest   DROP FOREIGN KEY `game_event_gameobject_quest_ibfk_2`;ALTER TABLE  game_event_gameobject_quest  ADD CONSTRAINT `game_event_gameobject_quest_ibfk_2` FOREIGN KEY (`quest`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE  game_event_gameobject_quest   DROP FOREIGN KEY `game_event_gameobject_quest_ibfk_3`;ALTER TABLE  game_event_gameobject_quest  ADD CONSTRAINT `game_event_gameobject_quest_ibfk_3` FOREIGN KEY (`event`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_model_equip   DROP FOREIGN KEY `game_event_model_equip_ibfk_1`;
ALTER TABLE  game_event_model_equip  ADD CONSTRAINT `game_event_model_equip_ibfk_1` FOREIGN KEY (`guid`) REFERENCES `creature` (`spawnID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_model_equip   DROP FOREIGN KEY `game_event_model_equip_ibfk_2`;ALTER TABLE  game_event_model_equip  ADD CONSTRAINT `game_event_model_equip_ibfk_2` FOREIGN KEY (`event`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_npc_vendor   DROP FOREIGN KEY `game_event_npc_vendor_ibfk_1`;
ALTER TABLE  game_event_npc_vendor  ADD CONSTRAINT `game_event_npc_vendor_ibfk_1` FOREIGN KEY (`event`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_npc_vendor   DROP FOREIGN KEY `game_event_npc_vendor_ibfk_2`;ALTER TABLE  game_event_npc_vendor  ADD CONSTRAINT `game_event_npc_vendor_ibfk_2` FOREIGN KEY (`guid`) REFERENCES `creature` (`spawnID`) ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE  game_event_npc_vendor   DROP FOREIGN KEY `game_event_npc_vendor_ibfk_3`;ALTER TABLE  game_event_npc_vendor  ADD CONSTRAINT `game_event_npc_vendor_ibfk_3` FOREIGN KEY (`item`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_npcflag   DROP FOREIGN KEY `game_event_npcflag_ibfk_1`;
ALTER TABLE  game_event_npcflag  ADD CONSTRAINT `game_event_npcflag_ibfk_1` FOREIGN KEY (`event_id`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_npcflag   DROP FOREIGN KEY `game_event_npcflag_ibfk_2`;ALTER TABLE  game_event_npcflag  ADD CONSTRAINT `game_event_npcflag_ibfk_2` FOREIGN KEY (`guid`) REFERENCES `creature` (`spawnID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_prerequisite   DROP FOREIGN KEY `game_event_prerequisite_ibfk_1`;
ALTER TABLE  game_event_prerequisite  ADD CONSTRAINT `game_event_prerequisite_ibfk_1` FOREIGN KEY (`event_id`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_prerequisite   DROP FOREIGN KEY `game_event_prerequisite_ibfk_2`;ALTER TABLE  game_event_prerequisite  ADD CONSTRAINT `game_event_prerequisite_ibfk_2` FOREIGN KEY (`prerequisite_event`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_quest_condition   DROP FOREIGN KEY `game_event_quest_condition_ibfk_1`;
ALTER TABLE  game_event_quest_condition  ADD CONSTRAINT `game_event_quest_condition_ibfk_1` FOREIGN KEY (`quest`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_quest_condition   DROP FOREIGN KEY `game_event_quest_condition_ibfk_2`;ALTER TABLE  game_event_quest_condition  ADD CONSTRAINT `game_event_quest_condition_ibfk_2` FOREIGN KEY (`event_id`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_seasonal_questrelation   DROP FOREIGN KEY `event_fk`;
ALTER TABLE  game_event_seasonal_questrelation  ADD CONSTRAINT `event_fk` FOREIGN KEY (`eventEntry`) REFERENCES `game_event` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  game_event_seasonal_questrelation   DROP FOREIGN KEY `quest_fk`;ALTER TABLE  game_event_seasonal_questrelation  ADD CONSTRAINT `quest_fk` FOREIGN KEY (`questId`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  gameobject   DROP FOREIGN KEY `gameobject_ibfk_2`;
ALTER TABLE  gameobject  ADD CONSTRAINT `gameobject_ibfk_2` FOREIGN KEY (`id`) REFERENCES `gameobject_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  gameobject_battleground   DROP FOREIGN KEY `gameobject_battleground_ibfk_1`;
ALTER TABLE  gameobject_battleground  ADD CONSTRAINT `gameobject_battleground_ibfk_1` FOREIGN KEY (`spawnID`) REFERENCES `gameobject` (`guid`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  gameobject_questender   DROP FOREIGN KEY `gameobject_questender_ibfk_2`;
ALTER TABLE  gameobject_questender  ADD CONSTRAINT `gameobject_questender_ibfk_2` FOREIGN KEY (`quest`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  gameobject_queststarter   DROP FOREIGN KEY `gameobject_queststarter_ibfk_2`;
ALTER TABLE  gameobject_queststarter  ADD CONSTRAINT `gameobject_queststarter_ibfk_2` FOREIGN KEY (`quest`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  gameobject_scripts   DROP FOREIGN KEY `gameobject_scripts_ibfk_1`;
ALTER TABLE  gameobject_scripts  ADD CONSTRAINT `gameobject_scripts_ibfk_1` FOREIGN KEY (`id`) REFERENCES `gameobject` (`guid`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  gossip_menu   DROP FOREIGN KEY `gossip_menu_ibfk_1`;
ALTER TABLE  gossip_menu  ADD CONSTRAINT `gossip_menu_ibfk_1` FOREIGN KEY (`TextID`) REFERENCES `gossip_text` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE gossip_menu_option DROP FOREIGN KEY `pk_action_menuId`;
ALTER TABLE gossip_menu_option ADD CONSTRAINT `pk_action_menuId` FOREIGN KEY (`ActionMenuID`) REFERENCES `gossip_menu` (`MenuID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE gossip_menu_option DROP FOREIGN KEY `pk_menuId`;
ALTER TABLE gossip_menu_option ADD CONSTRAINT `pk_menuId` FOREIGN KEY (`MenuID`) REFERENCES `gossip_menu` (`MenuID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_broadcast_text   DROP FOREIGN KEY `locales_broadcast_text_ibfk_1`;
ALTER TABLE  locales_broadcast_text  ADD CONSTRAINT `locales_broadcast_text_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `broadcast_text` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_creature   DROP FOREIGN KEY `locales_creature_ibfk_2`;
ALTER TABLE  locales_creature  ADD CONSTRAINT `locales_creature_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `creature_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_creature_text   DROP FOREIGN KEY `locales_creature_text_ibfk_1`;
ALTER TABLE  locales_creature_text  ADD CONSTRAINT `locales_creature_text_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `creature_text` (`CreatureID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_gameobject   DROP FOREIGN KEY `locales_gameobject_ibfk_2`;
ALTER TABLE  locales_gameobject  ADD CONSTRAINT `locales_gameobject_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `gameobject_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_gossip_menu_option   DROP FOREIGN KEY `locales_gossip_menu_option_ibfk_1`;
ALTER TABLE  locales_gossip_menu_option  ADD CONSTRAINT `locales_gossip_menu_option_ibfk_1` FOREIGN KEY (`menu_id`) REFERENCES `gossip_menu_option` (`MenuID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_gossip_text   DROP FOREIGN KEY `locales_gossip_text_ibfk_1`;
ALTER TABLE  locales_gossip_text  ADD CONSTRAINT `locales_gossip_text_ibfk_1` FOREIGN KEY (`id`) REFERENCES `gossip_text` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_item   DROP FOREIGN KEY `locales_item_ibfk_2`;
ALTER TABLE  locales_item  ADD CONSTRAINT `locales_item_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_page_text   DROP FOREIGN KEY `locales_page_text_ibfk_1`;
ALTER TABLE  locales_page_text  ADD CONSTRAINT `locales_page_text_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `page_text` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  locales_quest   DROP FOREIGN KEY `locales_quest_ibfk_1`;
ALTER TABLE  locales_quest  ADD CONSTRAINT `locales_quest_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  npc_vendor   DROP FOREIGN KEY `npc_vendor_ibfk_1`;
ALTER TABLE  npc_vendor  ADD CONSTRAINT `npc_vendor_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `creature_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  npc_vendor   DROP FOREIGN KEY `npc_vendor_ibfk_2`;ALTER TABLE  npc_vendor  ADD CONSTRAINT `npc_vendor_ibfk_2` FOREIGN KEY (`item`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pet_levelstats   DROP FOREIGN KEY `pet_levelstats_ibfk_2`;
ALTER TABLE  pet_levelstats  ADD CONSTRAINT `pet_levelstats_ibfk_2` FOREIGN KEY (`creature_entry`) REFERENCES `creature_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pet_name_generation   DROP FOREIGN KEY `pet_name_generation_ibfk_1`;
ALTER TABLE  pet_name_generation  ADD CONSTRAINT `pet_name_generation_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `creature_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE petcreateinfo_spell DROP FOREIGN KEY `petcreateinfo_spell_ibfk_1`;
ALTER TABLE petcreateinfo_spell ADD CONSTRAINT `petcreateinfo_spell_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `creature_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_items   DROP FOREIGN KEY `player_factionchange_items_ibfk_1`;
ALTER TABLE  player_factionchange_items  ADD CONSTRAINT `player_factionchange_items_ibfk_1` FOREIGN KEY (`alliance_id`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_items   DROP FOREIGN KEY `player_factionchange_items_ibfk_2`;ALTER TABLE  player_factionchange_items  ADD CONSTRAINT `player_factionchange_items_ibfk_2` FOREIGN KEY (`horde_id`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_items_race_specific   DROP FOREIGN KEY `player_factionchange_items_race_specific_ibfk_1`;
ALTER TABLE  player_factionchange_items_race_specific  ADD CONSTRAINT `player_factionchange_items_race_specific_ibfk_1` FOREIGN KEY (`item1`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_items_race_specific   DROP FOREIGN KEY `player_factionchange_items_race_specific_ibfk_2`;ALTER TABLE  player_factionchange_items_race_specific  ADD CONSTRAINT `player_factionchange_items_race_specific_ibfk_2` FOREIGN KEY (`item2`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_quests   DROP FOREIGN KEY `player_factionchange_quests_ibfk_1`;
ALTER TABLE  player_factionchange_quests  ADD CONSTRAINT `player_factionchange_quests_ibfk_1` FOREIGN KEY (`alliance_id`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_quests   DROP FOREIGN KEY `player_factionchange_quests_ibfk_2`;ALTER TABLE  player_factionchange_quests  ADD CONSTRAINT `player_factionchange_quests_ibfk_2` FOREIGN KEY (`horde_id`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_quests_race_specific   DROP FOREIGN KEY `player_factionchange_quests_race_specific_ibfk_1`;
ALTER TABLE  player_factionchange_quests_race_specific  ADD CONSTRAINT `player_factionchange_quests_race_specific_ibfk_1` FOREIGN KEY (`quest1`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_quests_race_specific   DROP FOREIGN KEY `player_factionchange_quests_race_specific_ibfk_2`;ALTER TABLE  player_factionchange_quests_race_specific  ADD CONSTRAINT `player_factionchange_quests_race_specific_ibfk_2` FOREIGN KEY (`quest2`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_spells   DROP FOREIGN KEY `player_factionchange_spells_ibfk_1`;
ALTER TABLE  player_factionchange_spells  ADD CONSTRAINT `player_factionchange_spells_ibfk_1` FOREIGN KEY (`alliance_id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_spells   DROP FOREIGN KEY `player_factionchange_spells_ibfk_2`;ALTER TABLE  player_factionchange_spells  ADD CONSTRAINT `player_factionchange_spells_ibfk_2` FOREIGN KEY (`horde_id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_spells_priest_specific   DROP FOREIGN KEY `player_factionchange_spells_priest_specific_ibfk_1`;
ALTER TABLE  player_factionchange_spells_priest_specific  ADD CONSTRAINT `player_factionchange_spells_priest_specific_ibfk_1` FOREIGN KEY (`spell1`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_spells_priest_specific   DROP FOREIGN KEY `player_factionchange_spells_priest_specific_ibfk_2`;ALTER TABLE  player_factionchange_spells_priest_specific  ADD CONSTRAINT `player_factionchange_spells_priest_specific_ibfk_2` FOREIGN KEY (`spell2`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_spells_specific   DROP FOREIGN KEY `player_factionchange_spells_specific_ibfk_1`;
ALTER TABLE  player_factionchange_spells_specific  ADD CONSTRAINT `player_factionchange_spells_specific_ibfk_1` FOREIGN KEY (`spell1`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  player_factionchange_spells_specific   DROP FOREIGN KEY `player_factionchange_spells_specific_ibfk_2`;ALTER TABLE  player_factionchange_spells_specific  ADD CONSTRAINT `player_factionchange_spells_specific_ibfk_2` FOREIGN KEY (`spell2`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  playercreateinfo_item   DROP FOREIGN KEY `playercreateinfo_item_ibfk_1`;
ALTER TABLE  playercreateinfo_item  ADD CONSTRAINT `playercreateinfo_item_ibfk_1` FOREIGN KEY (`itemid`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  playercreateinfo_spell   DROP FOREIGN KEY `playercreateinfo_spell_ibfk_1`;
ALTER TABLE  playercreateinfo_spell  ADD CONSTRAINT `playercreateinfo_spell_ibfk_1` FOREIGN KEY (`Spell`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_creature   DROP FOREIGN KEY `pool_creature_ibfk_1`;
ALTER TABLE  pool_creature  ADD CONSTRAINT `pool_creature_ibfk_1` FOREIGN KEY (`guid`) REFERENCES `creature` (`spawnID`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_creature   DROP FOREIGN KEY `pool_creature_ibfk_2`;ALTER TABLE  pool_creature  ADD CONSTRAINT `pool_creature_ibfk_2` FOREIGN KEY (`pool_entry`) REFERENCES `pool_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_gameobject   DROP FOREIGN KEY `pool_gameobject_ibfk_1`;
ALTER TABLE  pool_gameobject  ADD CONSTRAINT `pool_gameobject_ibfk_1` FOREIGN KEY (`guid`) REFERENCES `gameobject` (`guid`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_gameobject   DROP FOREIGN KEY `pool_gameobject_ibfk_2`;ALTER TABLE  pool_gameobject  ADD CONSTRAINT `pool_gameobject_ibfk_2` FOREIGN KEY (`pool_entry`) REFERENCES `pool_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_pool   DROP FOREIGN KEY `pool_pool_ibfk_1`;
ALTER TABLE  pool_pool  ADD CONSTRAINT `pool_pool_ibfk_1` FOREIGN KEY (`pool_id`) REFERENCES `pool_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_pool   DROP FOREIGN KEY `pool_pool_ibfk_2`;ALTER TABLE  pool_pool  ADD CONSTRAINT `pool_pool_ibfk_2` FOREIGN KEY (`mother_pool`) REFERENCES `pool_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_quest   DROP FOREIGN KEY `fk_pooltemplate`;
ALTER TABLE  pool_quest  ADD CONSTRAINT `fk_pooltemplate` FOREIGN KEY (`pool_entry`) REFERENCES `pool_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  pool_quest   DROP FOREIGN KEY `fk_quest`;ALTER TABLE  pool_quest  ADD CONSTRAINT `fk_quest` FOREIGN KEY (`entry`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  quest_details   DROP FOREIGN KEY `quest_details_ibfk_1`;
ALTER TABLE  quest_details  ADD CONSTRAINT `quest_details_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  quest_end_scripts   DROP FOREIGN KEY `quest_end_scripts_ibfk_1`;
ALTER TABLE  quest_end_scripts  ADD CONSTRAINT `quest_end_scripts_ibfk_1` FOREIGN KEY (`id`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  quest_mail_sender   DROP FOREIGN KEY `quest_mail_sender_ibfk_1`;
ALTER TABLE  quest_mail_sender  ADD CONSTRAINT `quest_mail_sender_ibfk_1` FOREIGN KEY (`QuestId`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  quest_offer_reward   DROP FOREIGN KEY `quest_offer_reward_ibfk_1`;
ALTER TABLE  quest_offer_reward  ADD CONSTRAINT `quest_offer_reward_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  quest_request_items   DROP FOREIGN KEY `quest_request_items_ibfk_1`;
ALTER TABLE  quest_request_items  ADD CONSTRAINT `quest_request_items_ibfk_1` FOREIGN KEY (`ID`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  quest_start_scripts   DROP FOREIGN KEY `quest_start_scripts_ibfk_1`;
ALTER TABLE  quest_start_scripts  ADD CONSTRAINT `quest_start_scripts_ibfk_1` FOREIGN KEY (`id`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  recovery_item   DROP FOREIGN KEY `recovery_item_ibfk_1`;
ALTER TABLE  recovery_item  ADD CONSTRAINT `recovery_item_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  recovery_spell   DROP FOREIGN KEY `recovery_spell_ibfk_1`;
ALTER TABLE  recovery_spell  ADD CONSTRAINT `recovery_spell_ibfk_1` FOREIGN KEY (`spell_id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  shop_items_random   DROP FOREIGN KEY `shop_items_random_ibfk_1`;
ALTER TABLE  shop_items_random  ADD CONSTRAINT `shop_items_random_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `item_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  skill_discovery_template   DROP FOREIGN KEY `skill_discovery_template_ibfk_2`;
ALTER TABLE  skill_discovery_template  ADD CONSTRAINT `skill_discovery_template_ibfk_2` FOREIGN KEY (`spellId`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  skill_extra_item_template   DROP FOREIGN KEY `skill_extra_item_template_ibfk_2`;
ALTER TABLE  skill_extra_item_template  ADD CONSTRAINT `skill_extra_item_template_ibfk_2` FOREIGN KEY (`spellId`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spawn_group   DROP FOREIGN KEY `spawn_group_ibfk_2`;
ALTER TABLE  spawn_group  ADD CONSTRAINT `spawn_group_ibfk_2` FOREIGN KEY (`groupId`) REFERENCES `spawn_group_template` (`groupId`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_affect   DROP FOREIGN KEY `spell_affect_ibfk_1`;
ALTER TABLE  spell_affect  ADD CONSTRAINT `spell_affect_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_area   DROP FOREIGN KEY `spell_area_ibfk_1`;
ALTER TABLE  spell_area  ADD CONSTRAINT `spell_area_ibfk_1` FOREIGN KEY (`spell`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_area   DROP FOREIGN KEY `spell_area_ibfk_2`;ALTER TABLE  spell_area  ADD CONSTRAINT `spell_area_ibfk_2` FOREIGN KEY (`quest_start`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE  spell_area   DROP FOREIGN KEY `spell_area_ibfk_3`;ALTER TABLE  spell_area  ADD CONSTRAINT `spell_area_ibfk_3` FOREIGN KEY (`quest_end`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_bonus_data   DROP FOREIGN KEY `spell_bonus_data_ibfk_1`;
ALTER TABLE  spell_bonus_data  ADD CONSTRAINT `spell_bonus_data_ibfk_1` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_custom_attr   DROP FOREIGN KEY `spell_custom_attr_ibfk_2`;
ALTER TABLE  spell_custom_attr  ADD CONSTRAINT `spell_custom_attr_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_disabled   DROP FOREIGN KEY `spell_disabled_ibfk_2`;
ALTER TABLE  spell_disabled  ADD CONSTRAINT `spell_disabled_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_elixir   DROP FOREIGN KEY `spell_elixir_ibfk_2`;
ALTER TABLE  spell_elixir  ADD CONSTRAINT `spell_elixir_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_group   DROP FOREIGN KEY `fk_group`;
ALTER TABLE  spell_group  ADD CONSTRAINT `fk_group` FOREIGN KEY (`id`) REFERENCES `spell_group_stack_rules` (`group_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_learn_spell   DROP FOREIGN KEY `spell_learn_spell_ibfk_3`;
ALTER TABLE  spell_learn_spell  ADD CONSTRAINT `spell_learn_spell_ibfk_3` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_learn_spell   DROP FOREIGN KEY `spell_learn_spell_ibfk_4`;ALTER TABLE  spell_learn_spell  ADD CONSTRAINT `spell_learn_spell_ibfk_4` FOREIGN KEY (`SpellID`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_pet_auras   DROP FOREIGN KEY `spell_pet_auras_ibfk_3`;
ALTER TABLE  spell_pet_auras  ADD CONSTRAINT `spell_pet_auras_ibfk_3` FOREIGN KEY (`spell`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_pet_auras   DROP FOREIGN KEY `spell_pet_auras_ibfk_4`;ALTER TABLE  spell_pet_auras  ADD CONSTRAINT `spell_pet_auras_ibfk_4` FOREIGN KEY (`aura`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_proc_event   DROP FOREIGN KEY `spell_proc_event_ibfk_2`;
ALTER TABLE  spell_proc_event  ADD CONSTRAINT `spell_proc_event_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_ranks   DROP FOREIGN KEY `spell_ranks_ibfk_1`;
ALTER TABLE  spell_ranks  ADD CONSTRAINT `spell_ranks_ibfk_1` FOREIGN KEY (`first_spell_id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_ranks   DROP FOREIGN KEY `spell_ranks_ibfk_2`;ALTER TABLE  spell_ranks  ADD CONSTRAINT `spell_ranks_ibfk_2` FOREIGN KEY (`spell_id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_required   DROP FOREIGN KEY `spell_required_ibfk_1`;
ALTER TABLE  spell_required  ADD CONSTRAINT `spell_required_ibfk_1` FOREIGN KEY (`spell_id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_required   DROP FOREIGN KEY `spell_required_ibfk_2`;ALTER TABLE  spell_required  ADD CONSTRAINT `spell_required_ibfk_2` FOREIGN KEY (`req_spell`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_scripts   DROP FOREIGN KEY `spell_scripts_ibfk_2`;
ALTER TABLE  spell_scripts  ADD CONSTRAINT `spell_scripts_ibfk_2` FOREIGN KEY (`id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_target_position   DROP FOREIGN KEY `spell_target_position_ibfk_1`;
ALTER TABLE  spell_target_position  ADD CONSTRAINT `spell_target_position_ibfk_1` FOREIGN KEY (`id`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  spell_threat   DROP FOREIGN KEY `spell_threat_ibfk_2`;
ALTER TABLE  spell_threat  ADD CONSTRAINT `spell_threat_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  trainer_spell   DROP FOREIGN KEY `trainer_spell_ibfk_1`;
ALTER TABLE  trainer_spell  ADD CONSTRAINT `trainer_spell_ibfk_1` FOREIGN KEY (`SpellId`) REFERENCES `spell_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  transport_events   DROP FOREIGN KEY `transport_events_ibfk_2`;
ALTER TABLE  transport_events  ADD CONSTRAINT `transport_events_ibfk_2` FOREIGN KEY (`entry`) REFERENCES `transports` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  war_effort   DROP FOREIGN KEY `war_effort_ibfk_1`;
ALTER TABLE  war_effort  ADD CONSTRAINT `war_effort_ibfk_1` FOREIGN KEY (`quest_id`) REFERENCES `quest_template` (`entry`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE  waypoint_info   DROP FOREIGN KEY `waypoint_info_ibfk_1`;
ALTER TABLE  waypoint_info  ADD CONSTRAINT `waypoint_info_ibfk_1` FOREIGN KEY (`id`) REFERENCES `waypoint_data` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
