ALTER TABLE `conditions`   
  ADD COLUMN `patch_min` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL AFTER `Comment`,
  ADD COLUMN `patch_max` TINYINT(3) UNSIGNED DEFAULT 10  NOT NULL AFTER `patch_min`,
  ENGINE=INNODB;
