UPDATE quest_template SET ReqCreatureOrGOId1 = 0, ReqCreatureOrGOCount1 = 0 WHERE entry IN (9962, 9967, 9970, 9972, 9973, 9977);
DELETE FROM creature_queststarter WHERE id = 22893;
DELETE FROM quest_start_scripts WHERE id IN (9962, 9967, 9970, 9972, 9973, 9977);

DELETE FROM smart_scripts WHERE entryorguid = 1847100 AND source_type = 9;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847100','9','0','0','0','0','100','0','13000','13000','0','0','0','1','1','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Gurgthock - On Script - Say Line 1');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847100','9','1','0','0','0','100','0','5000','5000','0','0','0','12','18398','1','120000','0','0','0','8','0','0','0','0','-704.669','7871.08','45.0387','1.59531','Gurgthock - On Script - Summon Creature \'Brokentoe\'');

DELETE FROM smart_scripts WHERE entryorguid = 1847102 AND source_type = 9;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847102','9','0','0','0','0','100','0','13000','13000','0','0','0','1','5','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Gurgthock - On Script - Say Line 5');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847102','9','1','0','0','0','100','0','5000','5000','0','0','0','12','18400','1','120000','0','0','0','8','0','0','0','0','-704.669','7871.08','45.0387','1.59531','Gurgthock - On Script - Summon Creature \'Rokdar the Sundered Lord\'');

DELETE FROM smart_scripts WHERE entryorguid = 18471 AND source_type = 0;
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','0','1','19','0','100','0','9962','0','0','0','0','1','0','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: Brokentoe\' Taken - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','1','20','61','0','100','512','9962','0','0','0','0','80','1847100','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: Brokentoe\' Taken - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','2','3','19','0','100','0','9967','0','0','0','0','1','0','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: The Blue Brothers\' Taken - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','3','20','61','0','100','512','9967','0','0','0','0','80','1847101','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: The Blue Brothers\' Taken - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','4','5','19','0','100','0','9970','0','0','0','0','1','0','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: Rokdar the Sundered Lord\' Taken - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','5','20','61','0','100','512','9970','0','0','0','0','80','1847102','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: Rokdar the Sundered Lord\' Taken - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','6','7','19','0','100','0','9972','0','0','0','0','1','0','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: Skra\'gath\' Taken - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','7','20','61','0','100','512','9972','0','0','0','0','80','1847103','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: Skra\'gath\' Taken - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','8','9','19','0','100','0','9973','0','0','0','0','1','0','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: The Warmaul Champion\' Taken - Say Line 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','9','20','61','0','100','512','9973','0','0','0','0','80','1847104','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: The Warmaul Champion\' Taken - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','10','11','19','0','100','0','9977','0','0','0','0','1','11','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: The Final Challenge\' Taken - Say Line 11');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','11','20','61','0','100','512','9977','0','0','0','0','45','1','1','0','0','0','0','19','18069','0','0','0','0','0','0','0','Gurgthock - On Quest \'The Ring of Blood: The Final Challenge\' Taken - Set Data 1 1');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','12','22','38','0','100','0','10','10','0','0','0','1','2','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Data Set 10 10 - Say Line 2');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','13','22','38','0','100','0','11','11','0','0','0','1','4','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Data Set 11 11 - Say Line 4');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','14','15','38','0','100','0','12','12','0','0','0','1','6','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Data Set 12 12 - Say Line 6');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','15','22','61','0','100','512','0','0','0','0','0','45','12','12','0','0','0','0','19','18069','0','0','0','0','0','0','0','Gurgthock - On Data Set 12 12 - Set Data 12 12');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','16','17','38','0','100','0','13','13','0','0','0','1','8','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Data Set 13 13 - Say Line 8');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','17','22','61','0','100','512','0','0','0','0','0','45','13','13','0','0','0','0','19','18069','0','0','0','0','0','0','0','Gurgthock - On Data Set 13 13 - Set Data 13 13');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','18','19','38','0','100','0','14','14','0','0','0','1','10','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Data Set 14 14 - Say Line 10');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','19','22','61','0','100','512','0','0','0','0','0','45','14','14','0','0','0','0','19','18069','0','0','0','0','0','0','0','Gurgthock - On Data Set 14 14 - Set Data 14 14');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','20','21','61','0','100','512','0','0','0','0','0','81','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Data Set 14 14 - Set Npc Flag Gossip');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','21','0','61','0','100','512','0','0','0','0','0','22','2','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - Link - Set Event Phase 2');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','22','23','61','0','100','512','0','0','0','0','0','81','3','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - Link - Set Npc Flags Gossip & Questgiver');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','23','27','61','0','100','512','0','0','0','0','0','22','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - Link - Set Event Phase 0');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','24','25','1','2','100','512','300000','300000','300000','300000','0','81','3','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - Out of Combat - Set Npc Flags Gossip & Questgiver (Phase 2)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','25','0','61','2','100','512','0','0','0','0','0','22','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - Out of Combat - Set Event Phase 0 (Phase 2)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','26','22','38','0','100','512','15','15','0','0','0','133','0','48191','0','0','0','0','1','0','0','0','0','0','0','0','0','Gurgthock - On Data Set 15 15 - Respawn Mogor');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','27','0','61','0','100','512','0','0','0','0','0','1','12','0','0','0','0','0','12','1','0','0','0','0','0','0','0','Gurgthock - On Data Set 15 15 - Say');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18471','0','28','0','19','0','100','0','0','0','0','0','0','64','1','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Gurgthock - On quest taken - Store target');

DELETE FROM smart_scripts WHERE entryorguid = 18069 AND source_type = 0;
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','0','0','0','0','100','0','1000','1000','3500','3500','0','11','16033','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Mogor - In Combat - Cast \'Chain Lightning\' (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','1','0','0','0','100','0','4000','4000','11000','13000','0','11','39529','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Mogor - In Combat - Cast \'Flame Shock\' (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','2','0','2','0','100','1','0','60','0','0','0','11','15982','1','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - Between 0-60% Health - Cast \'Healing Wave\' (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','3','0','2','0','100','1','0','30','0','0','0','11','28747','1','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - Between 0-30% Health - Cast \'Frenzy\' (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','4','0','2','0','100','1','0','30','0','0','0','1','0','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Mogor - Between 0-30% Health - Say Line 0 (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','5','0','6','0','100','513','0','0','0','0','0','80','1806901','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Just Died - Run Script (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','6','0','38','0','100','0','12','12','0','0','0','1','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Data Set 12 12 - Say Line 1 (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','7','0','38','0','100','0','13','13','0','0','0','1','2','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Data Set 13 13 - Say Line 2 (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','8','0','38','0','100','0','14','14','0','0','0','1','6','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Data Set 14 14 - Say Line 6 (No Repeat)');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','9','10','38','0','100','512','1','1','0','0','0','53','0','18069','0','0','0','1','1','0','0','0','0','0','0','0','0','Mogor - On Data Set 1 1 - Start Waypoint');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','10','0','61','0','100','512','0','0','0','0','0','1','3','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Mogor - On Data Set 1 1 - Say Line 3');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','11','12','40','0','100','512','4','18069','0','0','0','54','100000','0','2','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Waypoint 4 Reached - Pause Waypoint');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','12','0','61','0','100','512','0','0','0','0','0','80','1806900','2','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Waypoint 4 Reached - Run Script');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','13','0','21','0','100','512','0','0','0','0','0','2','35','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Reached Home - Set Faction 35');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','14','15','6','0','100','513','0','0','0','0','0','15','9977','0','0','0','0','0','27','0','0','0','0','0','0','0','0','Mogor - On Just Died - Quest Credit \'The Ring of Blood: The Final Challenge\'');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18069','0','15','0','61','0','100','512','0','0','0','0','0','45','15','15','0','0','0','0','19','18471','0','0','0','0','0','0','0','Mogor - Linked with Previous Event - Say Data');

DELETE FROM creature_text WHERE CreatureID IN (18069, 18471);
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','0','0','%s goes into a frenzy!','16','0','100','0','0','0','38630','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','1','0','Dat was poop! Mogor could put up much better fight den dat!','14','0','100','0','0','0','15470','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','2','0','Mogor not impressed! Skra\'gath wuz made of da air and shadow! Soft like da squishy orcies!','14','0','100','0','0','0','15474','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','3','0','Now you face da true champion! I give you chance to run away little one. Run away now before Mogor decim... destyor... Run away before Mogor KILL!','14','0','100','0','0','0','15478','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','4','0','No more chances! Now you pay da ogre!','14','0','100','15','0','0','15479','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','5','0','No more nice ogre! You hurt Mogor!!','14','0','100','0','0','0','15483','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18069','6','0','WUT!? UNPOSSIBLE!! You fight Mogor now! Mogor destroy!','14','0','100','0','0','0','15477','0','Mogor');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','0','0','Get in the Ring of Blood, $n. The fight is about to start!','12','0','100','0','0','0','15441','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','1','0','The battle is about to begin! $n versus the ferocious clefthoof, Brokentoe!','14','0','100','0','0','0','15439','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','2','0','$n has defeated Brokentoe!','14','0','100','0','0','0','15442','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','3','0','The battle is about to begin! The unmerciful Murkblood twins versus $n!','14','0','100','0','0','0','15461','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','4','0','Unbelievable! $n has defeated the Murkblood twins!','14','0','100','0','0','0','15462','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','5','0','Hailing from the mountains of Blade\'s Edge comes Rokdar the Sundered Lord! $n is in for the fight of $g his:her; life.','14','0','100','0','0','0','15467','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','6','0','$n is victorious once more!','14','0','100','0','0','0','15469','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','7','0','From parts unknown: Skra\'gath! Can $n possibly survive the onslaught of void energies?','14','0','100','0','0','0','15473','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','8','0','$n is victorious once more!','14','0','100','0','0','0','15469','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','9','0','This is the moment we\'ve all been waiting for! The Warmaul champion is about to make his first showing at the Ring of Blood in weeks! Will $n go down in defeat as easily as the champion\'s other opponents? We shall see...','14','0','100','0','0','0','15475','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','10','0','$n is victorious once more!','14','0','100','0','0','0','15469','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','11','0','Mogor has challenged you. You have to accept! Get in the ring if you are ready to fight.','12','0','100','0','0','0','15480','0','Gurgthock');
replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18471','12','0','$n has defeated the hero of the Warmaul, Mogor! All hail $n!','12','0','100','15','0','0','15482','2','Gurgthock');

replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847104','9','0','0','0','0','100','0','13000','13000','0','0','0','1','9','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Gurgthock - On Script - Say Line 9');
replace into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847104','9','1','0','0','0','100','0','5000','5000','0','0','0','12','18402','1','120000','0','0','0','8','0','0','0','0','-704.669','7871.08','45.0387','1.59531','Gurgthock - On Script - Summon Creature \'Warmaul Champion\'');


DELETE FROM smart_scripts WHERE entryorguid = 18398 AND source_type = 0;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18398','0','0','0','0','0','100','0','1000','1000','9000','11000','0','11','32023','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Brokentoe - In Combat - Cast \'Hoof Stomp\' (Phase 1) (No Repeat) (Dungeon)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18398','0','1','2','6','0','100','513','0','0','0','0','0','15','9962','0','0','0','0','0','27','0','0','0','0','0','0','0','0','Brokentoe - On Just Died - Quest Credit \'The Ring of Blood: Brokentoe\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18398','0','2','0','61','0','100','513','0','0','0','0','0','45','10','10','0','0','0','0','19','18471','0','0','0','0','0','0','0','Brokentoe - On Just Died - Set Data 10 10 (No Repeat)');


DELETE FROM smart_scripts WHERE entryorguid = 18402 AND source_type = 0;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','0','0','4','0','100','0','0','0','0','0','0','1','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Warmaul Champion - On Aggro - Say Line 0 (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','1','0','4','0','100','0','0','0','0','0','0','11','31403','1','0','0','0','0','1','0','0','0','0','0','0','0','0','Warmaul Champion - On Aggro - Cast \'Battle Shout\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','2','0','9','0','100','1','5','30','1500','2000','0','11','32323','1','0','0','0','0','2','0','0','0','0','0','0','0','0','Warmaul Champion - Within 5-30 Range - Cast \'Charge\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','3','0','0','0','100','0','3000','4000','6000','7000','0','11','15708','1','0','0','0','0','2','0','0','0','0','0','0','0','0','Warmaul Champion - In Combat - Cast \'Mortal Strike\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','4','0','0','0','100','0','1000','1000','9000','11000','0','11','17963','1','0','0','0','0','2','0','0','0','0','0','0','0','0','Warmaul Champion - In Combat - Cast \'Sundering Cleave\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','5','6','6','0','100','513','0','0','0','0','0','15','9973','0','0','0','0','0','27','0','0','0','0','0','0','0','0','Warmaul Champion - On Just Died - Quest Credit \'The Ring of Blood: The Warmaul Champion\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18402','0','6','0','61','0','100','513','0','0','0','0','0','45','14','14','0','0','0','0','19','18471','0','0','0','0','0','0','0','Warmaul Champion - On Just Died - Set Data 14 14 (No Repeat)');

replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18400','0','0','ROKDAR SMASH PUNY $n!','14','0','100','0','0','0','15468','0','Rokdar the Sundered Lord');

DELETE FROM smart_scripts WHERE entryorguid = 1847101 AND source_type = 9;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847101','9','0','0','0','0','100','0','13000','13000','0','0','0','1','3','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Gurgthock - On Script - Say Line 3');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847101','9','1','0','0','0','100','0','5000','5000','0','0','0','12','18399','1','120000','0','0','0','8','0','0','0','0','-717.852','7877.33','45.5474','1.59918','Gurgthock - On Script - Summon Creature \'Murkblood Twin\'');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847101','9','2','0','0','0','100','0','0','0','0','0','0','12','18399','1','120000','0','0','0','8','0','0','0','0','-695.944','7880.36','47.0975','2.08456','Gurgthock - On Script - Summon Creature \'Murkblood Twin\'');

DELETE FROM smart_scripts WHERE entryorguid = 18399 AND source_type = 0;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','0','0','4','0','100','0','0','0','0','0','0','1','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Murkblood Twin - On Aggro - Say Line 0 (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','1','0','0','0','100','0','1000','1000','2000','2000','0','11','14873','1','0','0','0','0','2','0','0','0','0','0','0','0','0','Murkblood Twin - In Combat - Cast \'Sinister Strike\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','2','0','0','0','100','0','5000','6000','11000','12000','0','11','15691','1','0','0','0','0','2','0','0','0','0','0','0','0','0','Murkblood Twin - In Combat - Cast \'Eviscerate\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','3','0','0','0','100','0','8000','9000','15000','16000','0','11','32319','1','0','0','0','0','2','0','0','0','0','0','0','0','0','Murkblood Twin - In Combat - Cast \'Mutilate\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','4','5','6','1','100','513','0','0','0','0','0','15','9967','0','0','0','0','0','27','0','0','0','0','0','0','0','0','Murkblood Twin - On Just Died - Quest Credit \'The Ring of Blood: The Blue Brothers\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','5','0','61','1','100','513','0','0','0','0','0','45','11','11','0','0','0','0','19','18471','0','0','0','0','0','0','0','Murkblood Twin - On Just Died - Set Data 11 11 (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','6','0','25','0','100','512','0','0','0','0','0','22','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Murkblood Twin - On Reset - Set Event Phase 0');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','7','0','7','0','100','512','0','0','0','0','0','41','0','0','0','0','0','0','1','0','0','100','0','0','0','0','0','Murkblood Twin - On evade - Despawn');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','8','0','6','0','100','512','0','0','0','0','0','45','1','1','0','0','0','0','9','18399','0','100','0','0','0','0','0','Murkblood Twin - On Just Died - Set Data 1 1');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','9','10','38','0','100','512','1','1','0','0','0','45','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Murkblood Twin - On Data Set 1 1 - Set Data 1 0');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18399','0','10','0','61','0','100','512','1','1','0','0','0','23','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Murkblood Twin - Linked with Previous Event - Increment Phase');

replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18399','0','0','Blue brothers reign supreme!','12','0','100','0','0','0','15460','0','Murkblood Twin');

DELETE FROM smart_scripts WHERE entryorguid = 18400 AND source_type = 0;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','0','0','4','0','100','1','0','0','0','0','0','1','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Rokdar the Sundered Lord - Out of Combat - Say Line 0 (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','1','0','0','0','100','0','1000','1000','9000','11000','0','11','16727','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Rokdar the Sundered Lord - In Combat - Cast \'War Stomp\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','2','0','31','0','100','0','31389','0','0','0','0','1','0','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Rokdar the Sundered Lord - On Target Spellhit \'Knock Away\' - Say Line 0 (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','3','0','0','0','100','0','6000','6000','12000','12000','0','11','31389','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Rokdar the Sundered Lord - In Combat - Cast \'Knock Away\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','4','0','0','0','100','0','20000','20000','25000','25000','0','11','15976','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Rokdar the Sundered Lord - In Combat - Cast \'Puncture\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','5','6','6','0','100','513','0','0','0','0','0','15','9970','0','0','0','0','0','27','0','0','0','0','0','0','0','0','Rokdar the Sundered Lord - On Just Died - Quest Credit \'The Ring of Blood: Rokdar the Sundered Lord\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18400','0','6','0','61','0','100','513','0','0','0','0','0','45','12','12','0','0','0','0','19','18471','0','0','0','0','0','0','0','Rokdar the Sundered Lord - On Just Died - Set Data 12 12 (No Repeat)');

DELETE FROM smart_scripts WHERE entryorguid = 1847103 AND source_type = 9;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847103','9','0','0','0','0','100','0','13000','13000','0','0','0','1','7','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Gurgthock - On Script - Say Line 7');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1847103','9','1','0','0','0','100','0','5000','5000','0','0','0','12','18401','1','120000','0','0','0','8','0','0','0','0','-704.669','7871.08','45.0387','1.59531','Gurgthock - On Script - Summon Creature \'Skra\'gath\'');


DELETE FROM smart_scripts WHERE entryorguid = 18401 AND source_type = 0;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18401','0','0','0','1','0','100','1','0','0','0','0','0','11','29299','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Skra\'gath - Out of Combat - Cast \'Draining Touch\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18401','0','1','0','4','0','100','0','0','0','0','0','0','1','0','0','0','0','0','0','7','0','0','0','0','0','0','0','0','Skra\'gath - On Aggro - Say Line 0 (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18401','0','2','0','0','0','100','0','6000','6000','12000','12000','0','11','32324','0','0','0','0','0','2','0','0','0','0','0','0','0','0','Skra\'gath - In Combat - Cast \'Shadow Burst\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18401','0','3','4','6','0','100','513','0','0','0','0','0','15','9972','0','0','0','0','0','27','0','0','0','0','0','0','0','0','Skra\'gath - On Just Died - Quest Credit \'The Ring of Blood: Skra\'gath\' (No Repeat)');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('18401','0','4','0','61','0','100','513','0','0','0','0','0','45','13','13','0','0','0','0','19','18471','0','0','0','0','0','0','0','Skra\'gath - On Just Died - Set Data 13 13 (No Repeat)');

replace into `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) values('18401','0','0','Closer... Come closer... See what the void brings!','14','0','100','0','0','0','15472','0','Skra\'gath');

DELETE FROM smart_scripts WHERE entryorguid = 1806900 AND source_type = 9;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1806900','9','0','0','0','0','100','0','0','0','0','0','0','1','4','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Script - Say Line 4');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1806900','9','1','0','0','0','100','0','5000','5000','0','0','0','2','14','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Script - Set Faction 14');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('1806900','9','2','0','0','0','100','0','9','9','0','0','0','8','2','0','0','0','0','0','1','0','0','0','0','0','0','0','0','Mogor - On Script - Set Reactstate Aggressive');


replace into `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) values('18069','1','-715.037','7922.95','59.5062','Mogor');
replace into `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) values('18069','2','-720.283','7916.27','57.1464','Mogor');
replace into `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) values('18069','3','-724.706','7909.14','51.8177','Mogor');
replace into `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) values('18069','4','-717.016','7896.94','48.4604','Mogor');
