ALTER TABLE `gossip_menu`   
  ADD COLUMN `patch_min` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  ADD COLUMN `patch_max` TINYINT(3) UNSIGNED DEFAULT 10  NOT NULL;

ALTER TABLE `gossip_menu_option`   
  ADD COLUMN `patch_min` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  ADD COLUMN `patch_max` TINYINT(3) UNSIGNED DEFAULT 10  NOT NULL;
