ALTER TABLE `locales_creature`  
  CHARSET=utf8, COLLATE=utf8_unicode_ci,
  CHANGE `name_loc1` `name_loc1` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc2` `name_loc2` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc3` `name_loc3` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc4` `name_loc4` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc5` `name_loc5` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc6` `name_loc6` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc7` `name_loc7` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc8` `name_loc8` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `subname_loc1` `subname_loc1` VARCHAR(100) NULL,
  CHANGE `subname_loc2` `subname_loc2` VARCHAR(100) NULL,
  CHANGE `subname_loc3` `subname_loc3` VARCHAR(100) NULL,
  CHANGE `subname_loc4` `subname_loc4` VARCHAR(100) NULL,
  CHANGE `subname_loc5` `subname_loc5` VARCHAR(100) NULL,
  CHANGE `subname_loc6` `subname_loc6` VARCHAR(100) NULL,
  CHANGE `subname_loc7` `subname_loc7` VARCHAR(100) NULL,
  CHANGE `subname_loc8` `subname_loc8` VARCHAR(100) NULL;

ALTER TABLE `locales_gameobject`   
  CHANGE `name_loc1` `name_loc1` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc2` `name_loc2` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc3` `name_loc3` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc4` `name_loc4` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc5` `name_loc5` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc6` `name_loc6` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc7` `name_loc7` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `name_loc8` `name_loc8` VARCHAR(100) DEFAULT '' NOT NULL,
  CHANGE `castbarcaption_loc1` `castbarcaption_loc1` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc2` `castbarcaption_loc2` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc3` `castbarcaption_loc3` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc4` `castbarcaption_loc4` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc5` `castbarcaption_loc5` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc6` `castbarcaption_loc6` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc7` `castbarcaption_loc7` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHANGE `castbarcaption_loc8` `castbarcaption_loc8` VARCHAR(100) DEFAULT ''  NOT NULL,
  CHARSET=utf8;

ALTER TABLE `locales_gossip_menu_option`  
  CHARSET=utf8, COLLATE=utf8_unicode_ci,
  CHANGE `option_text_loc1` `option_text_loc1` TEXT NULL,
  CHANGE `option_text_loc2` `option_text_loc2` TEXT NULL,
  CHANGE `option_text_loc3` `option_text_loc3` TEXT NULL,
  CHANGE `option_text_loc4` `option_text_loc4` TEXT NULL,
  CHANGE `option_text_loc5` `option_text_loc5` TEXT NULL,
  CHANGE `option_text_loc6` `option_text_loc6` TEXT NULL,
  CHANGE `option_text_loc7` `option_text_loc7` TEXT NULL,
  CHANGE `option_text_loc8` `option_text_loc8` TEXT NULL,
  CHANGE `box_text_loc1` `box_text_loc1` TEXT NULL,
  CHANGE `box_text_loc2` `box_text_loc2` TEXT NULL,
  CHANGE `box_text_loc3` `box_text_loc3` TEXT NULL,
  CHANGE `box_text_loc4` `box_text_loc4` TEXT NULL,
  CHANGE `box_text_loc5` `box_text_loc5` TEXT NULL,
  CHANGE `box_text_loc6` `box_text_loc6` TEXT NULL,
  CHANGE `box_text_loc7` `box_text_loc7` TEXT NULL,
  CHANGE `box_text_loc8` `box_text_loc8` TEXT NULL;

ALTER TABLE `locales_gossip_text`  
  CHARSET=utf8, COLLATE=utf8_unicode_ci,
  CHANGE `Text0_0_loc1` `Text0_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc2` `Text0_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc3` `Text0_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc4` `Text0_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc5` `Text0_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc6` `Text0_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc7` `Text0_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text0_0_loc8` `Text0_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc1` `Text0_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc2` `Text0_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc3` `Text0_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc4` `Text0_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc5` `Text0_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc6` `Text0_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc7` `Text0_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text0_1_loc8` `Text0_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc1` `Text1_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc2` `Text1_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc3` `Text1_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc4` `Text1_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc5` `Text1_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc6` `Text1_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc7` `Text1_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text1_0_loc8` `Text1_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc1` `Text1_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc2` `Text1_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc3` `Text1_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc4` `Text1_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc5` `Text1_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc6` `Text1_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc7` `Text1_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text1_1_loc8` `Text1_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc1` `Text2_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc2` `Text2_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc3` `Text2_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc4` `Text2_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc5` `Text2_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc6` `Text2_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc7` `Text2_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text2_0_loc8` `Text2_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc1` `Text2_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc2` `Text2_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc3` `Text2_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc4` `Text2_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc5` `Text2_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc6` `Text2_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc7` `Text2_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text2_1_loc8` `Text2_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc1` `Text3_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc2` `Text3_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc3` `Text3_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc4` `Text3_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc5` `Text3_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc6` `Text3_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc7` `Text3_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text3_0_loc8` `Text3_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc1` `Text3_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc2` `Text3_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc3` `Text3_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc4` `Text3_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc5` `Text3_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc6` `Text3_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc7` `Text3_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text3_1_loc8` `Text3_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc1` `Text4_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc2` `Text4_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc3` `Text4_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc4` `Text4_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc5` `Text4_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc6` `Text4_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc7` `Text4_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text4_0_loc8` `Text4_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc1` `Text4_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc2` `Text4_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc3` `Text4_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc4` `Text4_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc5` `Text4_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc6` `Text4_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc7` `Text4_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text4_1_loc8` `Text4_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc1` `Text5_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc2` `Text5_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc3` `Text5_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc4` `Text5_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc5` `Text5_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc6` `Text5_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc7` `Text5_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text5_0_loc8` `Text5_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc1` `Text5_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc2` `Text5_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc3` `Text5_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc4` `Text5_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc5` `Text5_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc6` `Text5_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc7` `Text5_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text5_1_loc8` `Text5_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc1` `Text6_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc2` `Text6_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc3` `Text6_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc4` `Text6_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc5` `Text6_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc6` `Text6_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc7` `Text6_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text6_0_loc8` `Text6_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc1` `Text6_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc2` `Text6_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc3` `Text6_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc4` `Text6_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc5` `Text6_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc6` `Text6_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc7` `Text6_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text6_1_loc8` `Text6_1_loc8` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc1` `Text7_0_loc1` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc2` `Text7_0_loc2` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc3` `Text7_0_loc3` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc4` `Text7_0_loc4` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc5` `Text7_0_loc5` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc6` `Text7_0_loc6` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc7` `Text7_0_loc7` longtext DEFAULT NULL,
  CHANGE `Text7_0_loc8` `Text7_0_loc8` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc1` `Text7_1_loc1` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc2` `Text7_1_loc2` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc3` `Text7_1_loc3` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc4` `Text7_1_loc4` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc5` `Text7_1_loc5` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc6` `Text7_1_loc6` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc7` `Text7_1_loc7` longtext DEFAULT NULL,
  CHANGE `Text7_1_loc8` `Text7_1_loc8` longtext DEFAULT NULL;
  
ALTER TABLE `locales_item`  
  CHARSET=utf8, COLLATE=utf8_unicode_ci,
  CHANGE `name_loc1` `name_loc1` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc2` `name_loc2` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc3` `name_loc3` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc4` `name_loc4` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc5` `name_loc5` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc6` `name_loc6` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc7` `name_loc7` varchar(100) NOT NULL DEFAULT '',
  CHANGE `name_loc8` `name_loc8` varchar(100) NOT NULL DEFAULT '',
  CHANGE `description_loc1` `description_loc1` varchar(255) DEFAULT NULL,
  CHANGE `description_loc2` `description_loc2` varchar(255) DEFAULT NULL,
  CHANGE `description_loc3` `description_loc3` varchar(255) DEFAULT NULL,
  CHANGE `description_loc4` `description_loc4` varchar(255) DEFAULT NULL,
  CHANGE `description_loc5` `description_loc5` varchar(255) DEFAULT NULL,
  CHANGE `description_loc6` `description_loc6` varchar(255) DEFAULT NULL,
  CHANGE `description_loc7` `description_loc7` varchar(255) DEFAULT NULL,
  CHANGE `description_loc8` `description_loc8` varchar(255) DEFAULT NULL;
  
ALTER TABLE `locales_page_text`  
  CHARSET=utf8, COLLATE=utf8_unicode_ci,
  CHANGE `Text_loc1` `Text_loc1` longtext DEFAULT NULL,
  CHANGE `Text_loc2` `Text_loc2` longtext DEFAULT NULL,
  CHANGE `Text_loc3` `Text_loc3` longtext DEFAULT NULL,
  CHANGE `Text_loc4` `Text_loc4` longtext DEFAULT NULL,
  CHANGE `Text_loc5` `Text_loc5` longtext DEFAULT NULL,
  CHANGE `Text_loc6` `Text_loc6` longtext DEFAULT NULL,
  CHANGE `Text_loc7` `Text_loc7` longtext DEFAULT NULL,
  CHANGE `Text_loc8` `Text_loc8` longtext DEFAULT NULL;

ALTER TABLE `locales_quest`  
  CHARSET=utf8, COLLATE=utf8_unicode_ci,
  CHANGE `Title_loc1` `Title_loc1` text DEFAULT NULL,
  CHANGE `Title_loc2` `Title_loc2` text DEFAULT NULL,
  CHANGE `Title_loc3` `Title_loc3` text DEFAULT NULL,
  CHANGE `Title_loc4` `Title_loc4` text DEFAULT NULL,
  CHANGE `Title_loc5` `Title_loc5` text DEFAULT NULL,
  CHANGE `Title_loc6` `Title_loc6` text DEFAULT NULL,
  CHANGE `Title_loc7` `Title_loc7` text DEFAULT NULL,
  CHANGE `Title_loc8` `Title_loc8` text DEFAULT NULL,
  CHANGE `Details_loc1` `Details_loc1` text DEFAULT NULL,
  CHANGE `Details_loc2` `Details_loc2` text DEFAULT NULL,
  CHANGE `Details_loc3` `Details_loc3` text DEFAULT NULL,
  CHANGE `Details_loc4` `Details_loc4` text DEFAULT NULL,
  CHANGE `Details_loc5` `Details_loc5` text DEFAULT NULL,
  CHANGE `Details_loc6` `Details_loc6` text DEFAULT NULL,
  CHANGE `Details_loc7` `Details_loc7` text DEFAULT NULL,
  CHANGE `Details_loc8` `Details_loc8` text DEFAULT NULL,
  CHANGE `Objectives_loc1` `Objectives_loc1` text DEFAULT NULL,
  CHANGE `Objectives_loc2` `Objectives_loc2` text DEFAULT NULL,
  CHANGE `Objectives_loc3` `Objectives_loc3` text DEFAULT NULL,
  CHANGE `Objectives_loc4` `Objectives_loc4` text DEFAULT NULL,
  CHANGE `Objectives_loc5` `Objectives_loc5` text DEFAULT NULL,
  CHANGE `Objectives_loc6` `Objectives_loc6` text DEFAULT NULL,
  CHANGE `Objectives_loc7` `Objectives_loc7` text DEFAULT NULL,
  CHANGE `Objectives_loc8` `Objectives_loc8` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc1` `OfferRewardText_loc1` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc2` `OfferRewardText_loc2` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc3` `OfferRewardText_loc3` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc4` `OfferRewardText_loc4` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc5` `OfferRewardText_loc5` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc6` `OfferRewardText_loc6` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc7` `OfferRewardText_loc7` text DEFAULT NULL,
  CHANGE `OfferRewardText_loc8` `OfferRewardText_loc8` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc1` `RequestItemsText_loc1` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc2` `RequestItemsText_loc2` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc3` `RequestItemsText_loc3` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc4` `RequestItemsText_loc4` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc5` `RequestItemsText_loc5` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc6` `RequestItemsText_loc6` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc7` `RequestItemsText_loc7` text DEFAULT NULL,
  CHANGE `RequestItemsText_loc8` `RequestItemsText_loc8` text DEFAULT NULL,
  CHANGE `EndText_loc1` `EndText_loc1` text DEFAULT NULL,
  CHANGE `EndText_loc2` `EndText_loc2` text DEFAULT NULL,
  CHANGE `EndText_loc3` `EndText_loc3` text DEFAULT NULL,
  CHANGE `EndText_loc4` `EndText_loc4` text DEFAULT NULL,
  CHANGE `EndText_loc5` `EndText_loc5` text DEFAULT NULL,
  CHANGE `EndText_loc6` `EndText_loc6` text DEFAULT NULL,
  CHANGE `EndText_loc7` `EndText_loc7` text DEFAULT NULL,
  CHANGE `EndText_loc8` `EndText_loc8` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc1` `ObjectiveText1_loc1` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc2` `ObjectiveText1_loc2` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc3` `ObjectiveText1_loc3` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc4` `ObjectiveText1_loc4` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc5` `ObjectiveText1_loc5` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc6` `ObjectiveText1_loc6` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc7` `ObjectiveText1_loc7` text DEFAULT NULL,
  CHANGE `ObjectiveText1_loc8` `ObjectiveText1_loc8` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc1` `ObjectiveText2_loc1` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc2` `ObjectiveText2_loc2` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc3` `ObjectiveText2_loc3` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc4` `ObjectiveText2_loc4` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc5` `ObjectiveText2_loc5` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc6` `ObjectiveText2_loc6` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc7` `ObjectiveText2_loc7` text DEFAULT NULL,
  CHANGE `ObjectiveText2_loc8` `ObjectiveText2_loc8` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc1` `ObjectiveText3_loc1` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc2` `ObjectiveText3_loc2` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc3` `ObjectiveText3_loc3` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc4` `ObjectiveText3_loc4` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc5` `ObjectiveText3_loc5` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc6` `ObjectiveText3_loc6` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc7` `ObjectiveText3_loc7` text DEFAULT NULL,
  CHANGE `ObjectiveText3_loc8` `ObjectiveText3_loc8` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc1` `ObjectiveText4_loc1` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc2` `ObjectiveText4_loc2` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc3` `ObjectiveText4_loc3` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc4` `ObjectiveText4_loc4` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc5` `ObjectiveText4_loc5` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc6` `ObjectiveText4_loc6` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc7` `ObjectiveText4_loc7` text DEFAULT NULL,
  CHANGE `ObjectiveText4_loc8` `ObjectiveText4_loc8` text DEFAULT NULL;
  