/*
SQLyog Community
MySQL - 10.3.10-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2000','|cff00ff00New ticket from|r|cffff00ff %s.|r |cff00ff00Ticket entry:|r|cffff00ff %d.|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2001','|cff00ff00Character|r|cffff00ff %s |r|cff00ff00edited his/her ticket:|r|cffff00ff %d.|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2002','|cff00ff00Character|r|cffff00ff %s |r|cff00ff00abandoned ticket entry:|r|cffff00ff %d.|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2003','|cff00ff00Closed by|r:|cff00ccff %s|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2004','|cff00ff00Deleted by|r:|cff00ccff %s|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2005','Ticket not found.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2006','Please close ticket before deleting it permanently.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2007','Ticket %d is already assigned.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2008','%u Tickets succesfully reloaded from the database.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2009','Showing list of open tickets.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2010','Showing list of open tickets whose creator is online.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2011','Showing list of closed tickets.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2012','Invalid name specified. The name must be a name of an online Game Master.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2013','This ticket is already assigned to yourself. To unassign use .ticket unassign %d and then reassign.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2014','Ticket %d is not assigned, you cannot unassign it.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2015','You cannot unassign tickets from staff members with a higher security level than yourself.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2016','Cannot close ticket %d, it is assigned to another GM.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2017','|cffaaffaaTicket|r:|cffaaccff %d.|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2018','|cff00ff00Created by|r:|cff00ccff %s|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2019','|cff00ff00Last change|r:|cff00ccff %s ago|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2020','|cff00ff00Assigned to|r:|cff00ccff %s|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2021','|cff00ff00Unassigned by|r:|cff00ccff %s|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2022','|cff00ff00Ticket Message|r: [%s]|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2023','|cff00ff00GM Comment|r: [%s]|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2024','|cff00ccff%s|r |cff00ff00Added comment|r: [%s]|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2025','|cff00ff00Created|r:|cff00ccff %s ago|r ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2027','There are pending open tickets, please close them first!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2028','All closed tickets were deleted and counter is reseted to |cffff00ff 1|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2029','|cff00ff00Ticket Response|r: [%s]|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('2030','|cff00ff00Completed by|r:|cff00ccff %s|r',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('6608','You cannot write tickets until you become level %d.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('1134','Sending tickets is allowed.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
replace into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values('1135','Sending tickets is not allowed.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

DELETE FROM command WHERE name LIKE "ticket%";
replace into `command` (`name`, `security`, `help`) values('ticket',					'1','Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands');
replace into `command` (`name`, `security`, `help`) values('ticket assign',				'1','Usage: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.');
replace into `command` (`name`, `security`, `help`) values('ticket close',				'1','Usage: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.');
replace into `command` (`name`, `security`, `help`) values('ticket closedlist',			'1','Displays a list of closed GM tickets.');
replace into `command` (`name`, `security`, `help`) values('ticket comment',			'1','Usage: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.');
replace into `command` (`name`, `security`, `help`) values('ticket complete',			'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket delete',				'1','Usage: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.');
replace into `command` (`name`, `security`, `help`) values('ticket escalate',			'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket escalatedlist',		'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket list',				'1','Displays a list of open GM tickets.');
replace into `command` (`name`, `security`, `help`) values('ticket onlinelist',			'1','Displays a list of open GM tickets whose owner is online.');
replace into `command` (`name`, `security`, `help`) values('ticket reset',				'1','Syntax: .ticket reset\nRemoves all closed tickets and resets the counter, if no pending open tickets are existing.');
replace into `command` (`name`, `security`, `help`) values('ticket response',			'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket response append',	'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket response appendln',	'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket togglesystem',		'1','Syntax: ');
replace into `command` (`name`, `security`, `help`) values('ticket unassign',			'1','Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.');
replace into `command` (`name`, `security`, `help`) values('ticket viewid',				'1','Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.');
replace into `command` (`name`, `security`, `help`) values('ticket viewname',			'1','Usage: .ticket viewname $creatorname. \r\nReturns details about specified ticket. Ticket must be open and not deleted.');
