ALTER TABLE guild DROP COLUMN IF EXISTS website;
ALTER TABLE guild DROP COLUMN IF EXISTS orientation;
ALTER TABLE guild DROP COLUMN IF EXISTS lang;
ALTER TABLE guild DROP COLUMN IF EXISTS description;