option(DO_DEBUG "Debug mode (No optimization and debug symbols)" 0)
option(DO_WARN "Enable all compilation warnings" 0)
option(TOOLS "Build map/vmap/mmap extraction/assembler tools" 1)
option(PLAYERBOT "Include playerbot system (DO NOT USE, WIP, not compiling)" 0)
option(TESTS "Include tests fonctionalities" 0)
option(USE_GPERFTOOLS "Include profiling capabilities from gperftools" 0)