option(DO_DEBUG "Debug mode (No optimization and debug symbols)" 0)
option(DO_WARN "Enable all compilation warnings" 0)
option(TOOLS "Build map/vmap/mmap extraction/assembler tools" 1)
option(PLAYERBOT "Include playerbot system (DO NOT USE, WIP, not compiling)" 0)
option(TESTS "Include tests fonctionalities" 0)
option(USE_GPERFTOOLS "Include profiling capabilities from gperftools" 0)
option(LICH_KING "NYI Lich King realm" 0)
option(BUILD_335_SUPPORT "NYI Realm supports 3.3.5 client" 0)
#more clang options 
if(DO_DEBUG)
option(CLANG_ADDRESS_SANITIZER "Enable clang AddressSanitizer (~2x slowdown)" 0)
option(CLANG_THREAD_SANITIZER "Enable clang ThreadSanitizer (~5-15x slowdown and 5-10x memory overhead)" 0)
option(CLANG_MEMORY_SANITIZER "Enable clang MemorySanitizer (~3x slowdown)" 0)
option(CLANG_THREAD_SAFETY_ANALYSIS "Enable clang Thread Safety Analysis (compile time only)" 0)
endif()